%% baselineAnalysis

%% Initialization
% ref: Main.m
addpath(genpath([pwd,'/_Functions']));  % Matlab functions for cost function and running cases - READ ONLY
addpath(genpath([pwd,'/_Controller'])); % Simulink model, where user scripts and models are placed

%% Load the baseline results
% These are generated by `MainParsimRun.m` and saving `simOut`
load _BaselineResults/baselineResults

nCases = length(simOut); % Number of simulation cases

% Emulate the `folders` variable in `Main.m` that used in legends
folders = {'', 'Baseline Results'};

%% Show the importance of each component to total cost

caseN = 1; % This plot will be the same of all cases

fCostFunctionPlot (simOut(caseN).CF, simOut(caseN).CF_Comp, ...
    simOut(caseN).CF_Vars, {simOut(caseN).CF_Freq}, ...
    simOut(caseN).pMetrics, folders, 'absFreq');

%% Determine correlation between signals
assert(~any(diff(cellfun(@length,{simOut.ChanName}))), ...
    'Some cases have different number of channels');
nChannels = length(simOut(1).ChanName);
rmsChans = zeros(nChannels,nCases);
for caseN = 1:nCases

    % Some channels do not contain valid data
    validChans = all(simOut(caseN).Channels ~= 0, 1);
    validChanNames = simOut(caseN).ChanName(validChans);
    
    % Normalize each column, preserving sign
    % ref: https://www.mathworks.com/matlabcentral/answers/372602-normalizing-columns-does-my-function-do-the-same-as-normc#answer_295940
    normc_fcn = @(m) sqrt(m.^2 ./ sum(m.^2)) .* sign(m);
    rmsChans(:,caseN) = rms(simOut(caseN).Channels);
    normChans = normc_fcn(simOut(caseN).Channels(:,validChans));
    
    % Calculate the correlation matrix
    R = corrcoef(normChans);
    
    figure('windowstyle','docked');
    heatmap(...
        simOut(caseN).ChanName(validChans), ...
        simOut(caseN).ChanName(validChans), ...
        R)
    
    % Calculate the PCA
    [coef,~,latent] = pca(normChans);
    
    figure('windowstyle','docked');
    heatmap(...
        [num2str((1:sum(validChans))') ...
            repmat('-',sum(validChans),1) ...
            num2str(latent,'%0.1E')], ...
        validChanNames, ...
        coef)
end

%%  Compute mean and RMS
allData = cell2mat({simOut.Channels}');
allMean = mean(allData);
allRMS = rms(allData - allMean);